[project]
name = "mydoctor-api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "Django==5.2",
    "asgiref>=3.8.1",
    "sqlparse>=0.5.0",
    "tzdata",
    "django-cors-headers>=4.3.0",
    "whitenoise>=6.6.0",
    "psycopg[binary]>=3.2.0",
]

[tool.vercel]
entrypoint = "projeto.wsgi:application"
