# Generated by Django 5.2 on 2025-09-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_chatroom_consulta_medico_consulta_medico_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
