# Generated by Django 5.2 on 2025-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_medico_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('clinico', 'Clínico Geral'), ('pediatria', 'Pediatria'), ('ginecologia', 'Ginecologia'), ('cardiologia', 'Cardiologia'), ('dermatologia', 'Dermatologia'), ('ortopedia', 'Ortopedia'), ('otorrino', 'Otorrinolaringologia'), ('oftalmo', 'Oftalmologia'), ('neuro', 'Neurologia'), ('psiquiatria', 'Psiquiatria')], max_length=64),
        ),
    ]
