# Generated by Django 5.2 on 2025-10-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_medico_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
