# Generated by Django 5.2 on 2025-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_chatroom_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='destinatario',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
